### ISSUE TITLE
Where should one create the Makefile, with respect to project strutcture?

### ISSUE THREAD

**Issue by abhi-jha** [pyk/cmake-tutorial#2]
Also, cmake isn't generating a binary while `cc main.cc` does. Is it by design?

**Comment by pyk** [comment]
> Where should one create the Makefile, with respect to project strutcture?

You should create `Makefile` in the root project directory (`cmake-tutorial/Makefile`).
If you run:

    cmake .

in the root project directory, the `Makefile` is generated for you.


> Also, cmake isn't generating a binary while cc main.cc does. Is it by design?

To generate the binary, run the following commands:

    cmake .
    make cmake-tutorial

`cmake .` command will generate the `Makefile` then `make cmake-tutorial` will generate the binary `cmake-tutorial` on the current directory (`cmake-tutorial/`).

**Comment by abhi-jha** [comment]
Thanks.
